name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-json
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --json=results.json || { echo "pytest failed"; exit 1; }
      continue-on-error: true
    - name: Check if results.json exists
      run: |
        if [ -f results.json ]; then
          echo "results.json exists"
        else
          echo "results.json does not exist"
          exit 1
        fi
    - name: Generate badge URL
      id: badge
      run: |
        total_tests=$(jq '.summary.passed + .summary.failed' results.json)
        passed_tests=$(jq '.summary.passed' results.json)
        if [ "$passed_tests" -eq "$total_tests" ]; then
          badge_color="brightgreen"
          badge_text="passed"
        else
          badge_color="red"
          badge_text="failed"
        fi
        badge_url="https://img.shields.io/badge/tests-${badge_text}-${badge_color}"
        echo "badge_url=$badge_url" >> $GITHUB_ENV
    - name: Update README with badge
      run: |
        sed -i "s|!\\[pytest badge\\](.*)|![pytest badge](${{ env.badge_url }})|g" README.md
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git commit -m "docs: update README.md with pytest badge" || echo "No changes to commit"
    - name: Push changes to README
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
