name: Update Badges

on:
  workflow_run:
    workflows: ["Static Analysis"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate badge URLs
        id: badge
        run: |
          flake8_issues=$(grep -c '' flake8_report.txt)
          pylint_score=$(grep -oP "Your code has been rated at \K[\d.]+\/10" pylint_report.txt)
          
          flake8_badge="https://img.shields.io/badge/flake8-${flake8_issues}_issues-red"
          pylint_badge="https://img.shields.io/badge/pylint-${pylint_score}-green"

          echo "flake8_badge=$flake8_badge" >> $GITHUB_ENV
          echo "pylint_badge=$pylint_badge" >> $GITHUB_ENV

      - name: Update README with badges
        run: |
          sed -i "s|!\\[Flake8\\](.*)|![Flake8](${{ env.flake8_badge }})|g" README.md
          sed -i "s|!\\[Pylint\\](.*)|![Pylint](${{ env.pylint_badge }})|g" README.md

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions'
          author_email: 'github-actions@github.com'
          message: 'Update README.md with latest badges'
